load ./evm.maude

reduce ( stack    mt
       | program  (0 -> PUSH(5)), (1 -> PUSH(5)), (2 -> ADD)
       | pc       0 
       | gas      10000 )
       .

reduce ( stack    mt
       | program  (0 -> PUSH(3)), (1 -> PUSH(5)), (2 -> SUB)
       | pc       0 
       | gas      10000 )
       .

reduce ( stack    mt
       | program  (0 -> PUSH(5)), (1 -> PUSH(3)), (2 -> SUB)
       | pc       0 
       | gas      10000 )
       .
quit
